print("Halo, ADKSP. Joszh!!!")
print("Hai, ADKSP!")
print("Assalamualaikum, ADKSP!")
print("Selamat pagi, ADKSP!")
print("Selamat siang, ADKSP!")
print("Selamat sore, ADKSP!")
print("Selamat malam, ADKSP!")
print("Apa kabar, ADKSP?")
print("Salam semangat, ADKSP!")
print("Semoga harimu menyenangkan, ADKSP!")
print("Sukses selalu, ADKSP!")
